
export const LOAD_ARTICLE_REQUEST = 'LOAD_ARTICLE_REQUEST';
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS';
export const LOAD_ARTICLE_FAILURE = 'LOAD_ARTICLE_FAILURE';

// export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
// export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
// export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export const LOAD_ARTICLES_META_SUCCESS = 'LOAD_ARTICLES_META_SUCCESS';
export const LOAD_ARTICLES_META_FAILURE = 'LOAD_ARTICLES_META_FAILURE';
export const LOAD_ARTICLES_META_REQUEST = 'LOAD_ARTICLES_META_REQUEST';

export const NAVIGATE_NEXT_ARTICLE_SECTION = 'NAVIGATE_NEXT_ARTICLE_SECTION';
export const NAVIGATE_PREVIOUS_ARTICLE_SECTION = 'NAVIGATE_PREVIOUS_ARTICLE_SECTION';
